version: '3.8'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: kanha456
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql

  server:
    build: ./server
    command: npm start
    environment:
      PORT: 8000
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: kanha456
      DB_DATABASE: asset_management_advanze
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./server:/app
      - /app/node_modules

  client:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:8000/api
    volumes:
      - ./client:/app
      - /app/node_modules

volumes:
  db-data:
